version: '3'
services:
  ingress:
    image: geosocio/ingress
    links:
      - api
      - web
  api:
    image: boggs/api
    env_file:
      - .env
    volumes:
      - database:/var/www/var/data
  web:
    build:
      context: ./
    image: boggs/web
    links:
      - api
volumes:
  database:
